---
- name: 'Install dependencies'
  ansible.builtin.apt:
    pkg:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - mysql-server
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      - python3-pymysql
    update_cache: yes
  become: yes